version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: my-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234  # Contraseña para el usuario root
      MYSQL_DATABASE: biblioteca  # Nombre de la base de datos a crear
    ports:
      - "3307:3306"  # Ahora escucha en localhost:3307
    volumes:
      - ./docs/init_encrypted.sql:/docker-entrypoint-initdb.d/init.sql  # Archivo de inicialización
      - db_data:/var/lib/mysql  # Persistencia de datos

volumes:
  db_data:
